export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const SUCCESS_CLEAR = "SUCCESS_CLEAR";
export const ERROR_CLEAR = "ERROR_CLEAR";
export const CLEAR = "CLEAR";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const GET_PROFILE_START = "GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const DELETE_PROFILE_START = "DELETE_PROFILE_START";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAILURE = "DELETE_PROFILE_FAILURE";
export const CHANGE_SUCCESS = "CHANGE_SUCCESS";

export const GET_USER_DETAILS_START = "GET_USER_DETAILS_START";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const CREATE_TODO_START = "CREATE_TODO_START";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE";

export const GET_TODO_START = "GET_TODO_START";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";

export const UPDATE_TODO_START = "UPDATE_TODO_START";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAILURE = "UPDATE_TODO_FAILURE";

export const DELETE_TODO_START = "DELETE_TODO_START";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";

export const GENERATE_DESCRIPTION_START = "GENERATE_DESCRIPTION_START";
export const GENERATE_DESCRIPTION_SUCCESS = "GENERATE_DESCRIPTION_SUCCESS";
export const GENERATE_DESCRIPTION_FAILURE = "GENERATE_DESCRIPTION_FAILURE";

export const CREATE_TODO_FOR_USER_START = "CREATE_TODO_FOR_USER_START";
export const CREATE_TODO_FOR_USER_SUCCESS = "CREATE_TODO_FOR_USER_SUCCESS";
export const CREATE_TODO_FOR_USER_FAILURE = "CREATE_TODO_FOR_USER_FAILURE";

export const GET_TODO_FOR_USER_START = "GET_TODO_FOR_USER_START";
export const GET_TODO_FOR_USER_SUCCESS = "GET_TODO_FOR_USER_SUCCESS";
export const GET_TODO_FOR_USER_FAILURE = "GET_TODO_FOR_USER_FAILURE";

export const UPDATE_TODO_FOR_USER_START = "UPDATE_TODO_FOR_USER_START";
export const UPDATE_TODO_FOR_USER_SUCCESS = "UPDATE_TODO_FOR_USER_SUCCESS";
export const UPDATE_TODO_FOR_USER_FAILURE = "UPDATE_TODO_FOR_USER_FAILURE";

export const DELETE_TODO_FOR_USER_START = "DELETE_TODO_FOR_USER_START";
export const DELETE_TODO_FOR_USER_SUCCESS = "DELETE_TODO_FOR_USER_SUCCESS";
export const DELETE_TODO_FOR_USER_FAILURE = "DELETE_TODO_FOR_USER_FAILURE";

export const CREATE_QA_FOR_USER_START = "CREATE_QA_FOR_USER_START";
export const CREATE_QA_FOR_USER_SUCCESS = "CREATE_QA_FOR_USER_SUCCESS";
export const CREATE_QA_FOR_USER_FAILURE = "CREATE_QA_FOR_USER_FAILURE";

export const GET_QA_OF_USER_START = "GET_QA_OF_USER_START";
export const GET_QA_OF_USER_SUCCESS = "GET_QA_OF_USER_SUCCESS";
export const GET_QA_OF_USER_FAILURE = "GET_QA_OF_USER_FAILURE";

export const UPDATE_QA_FOR_USER_START = "UPDATE_QA_FOR_USER_START";
export const UPDATE_QA_FOR_USER_SUCCESS = "UPDATE_QA_FOR_USER_SUCCESS";
export const UPDATE_QA_FOR_USER_FAILURE = "UPDATE_QA_FOR_USER_FAILURE";

export const DELETE_QA_FOR_USER_START = "DELETE_QA_FOR_USER_START";
export const DELETE_QA_FOR_USER_SUCCESS = "DELETE_QA_FOR_USER_SUCCESS";
export const DELETE_QA_FOR_USER_FAILURE = "DELETE_QA_FOR_USER_FAILURE";

export const CREATE_QA_START = "CREATE_QA_START";
export const CREATE_QA_SUCCESS = "CREATE_QA_SUCCESS";
export const CREATE_QA_FAILURE = "CREATE_QA_FAILURE";

export const GET_QA_START = "GET_QA_START";
export const GET_QA_SUCCESS = "GET_QA_SUCCESS";
export const GET_QA_FAILURE = "GET_QA_FAILURE";

export const UPDATE_QA_START = "UPDATE_QA_START";
export const UPDATE_QA_SUCCESS = "UPDATE_QA_SUCCESS";
export const UPDATE_QA_FAILURE = "UPDATE_QA_FAILURE";

export const DELETE_QA_START = "DELETE_QA_START";
export const DELETE_QA_SUCCESS = "DELETE_QA_SUCCESS";
export const DELETE_QA_FAILURE = "DELETE_TODO_FAILURE";

export const GENERATE_ANSWER_START = "GENERATE_ANSWER_START";
export const GENERATE_ANSWER_SUCCESS = "GENERATE_ANSWER_SUCCESS";
export const GENERATE_ANSWER_FAILURE = "GENERATE_ANSWER_FAILURE";

export const UPDATE_PASSWORD_START = "UPDATE_PASSWORD_START";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const SEARCH = "SEARCH";
